export const architectureMeta = {
  id: 'bca-blueprint-v1',
  name: 'Conrad Blueprint Explorer',
  version: '1.0.0',
  asOf: '2026-07-14',
  sourceOfTruthCoordinator: 'Conrad / EXPO',
  parentSystem: 'Blue Collar Apps OS',
  decisionNotice: 'ARCHITECTURE-LEVEL — route through Conrad / EXPO.',
}

const base = {
  status: 'UNVERIFIED',
  evidenceState: 'DOCUMENTED',
  owner: 'Architecture governance',
  parentId: null,
  capabilities: [],
  dependencies: [],
  repositories: [],
  environments: [],
  agents: [],
  workflows: [],
  riskLevel: 'UNKNOWN',
  decisionState: 'REVIEW REQUIRED',
  lastVerifiedAt: null,
  verifiedBy: null,
  sourceReferences: ['BCA Master Portfolio Register'],
}

const node = (record) => ({ ...base, ...record })

export const nodes = [
  node({
    id: 'bca-os',
    name: 'Blue Collar Apps OS',
    shortDescription: 'Founder-controlled parent operating system.',
    description: 'The parent system for company intake, projects, products, agents, governed knowledge, and founder-controlled operations.',
    nodeType: 'platform',
    status: 'WORKBENCH',
    evidenceState: 'VERIFIED',
    owner: 'Founder-controlled',
    capabilities: ['Company operating layer', 'Governed intake', 'System coordination'],
    repositories: ['Cmooreculinary/BCA-OS'],
    environments: ['Local', 'Render configuration documented'],
    agents: ['Conrad / EXPO'],
    workflows: ['Founder intake', 'Routing receipt', 'Audit logging'],
    riskLevel: 'HIGH',
    decisionState: 'GOVERNED',
    lastVerifiedAt: '2026-07-14',
    verifiedBy: 'Repository and portfolio audit',
    sourceReferences: ['BCA-OS README', 'BCA Master Portfolio Register'],
  }),
  node({
    id: 'conrad',
    name: 'Conrad / EXPO',
    shortDescription: 'Company brain, expediter, router, guide, and coordinator.',
    description: 'Conrad sits beneath BCA OS and coordinates intake, routing, source access, and approved model or agent use. The explorer is a governed map Conrad uses; it is not Conrad itself.',
    nodeType: 'executive-agent',
    status: 'WORKBENCH',
    evidenceState: 'VERIFIED',
    owner: 'Founder-controlled',
    parentId: 'bca-os',
    capabilities: ['Intake routing', 'Company guidance', 'Source coordination', 'Model and agent orchestration'],
    dependencies: ['bca-os', 'knowledge-vault', 'model-router', 'agent-registry', 'workflow-engine'],
    repositories: ['Cmooreculinary/BCA-OS'],
    agents: ['Conrad / EXPO'],
    workflows: ['Classify intake', 'Infer destination', 'Redact likely secrets', 'Return routing receipt'],
    riskLevel: 'HIGH',
    decisionState: 'ARCHITECTURE-LEVEL',
    lastVerifiedAt: '2026-07-14',
    verifiedBy: 'Repository and portfolio audit',
    sourceReferences: ['BCA-OS README', 'BCA Master Portfolio Register'],
  }),
  node({
    id: 'company-control',
    name: 'Company Control',
    shortDescription: 'Governed internal views for architecture, status, and founder decisions.',
    description: 'The internal experience layer for architecture visibility, founder oversight, and decision review.',
    nodeType: 'system-group',
    status: 'WORKBENCH',
    owner: 'Founder-controlled',
    parentId: 'bca-os',
    capabilities: ['Architecture visibility', 'Founder oversight', 'Decision review'],
    dependencies: ['conrad'],
    riskLevel: 'MEDIUM',
    decisionState: 'GOVERNED',
  }),
  node({
    id: 'shared-services',
    name: 'Shared Platform Services',
    shortDescription: 'Reusable infrastructure and governance beneath BCA products.',
    description: 'Shared services support multiple BCA products without allowing a customer application to become the company operating system.',
    nodeType: 'system-group',
    status: 'WORKBENCH',
    parentId: 'bca-os',
    capabilities: ['Shared infrastructure', 'Cross-product governance', 'Reusable controls'],
    dependencies: ['conrad'],
    riskLevel: 'HIGH',
    decisionState: 'ARCHITECTURE-LEVEL',
  }),
  node({
    id: 'product-suite',
    name: 'BCA Product Suite',
    shortDescription: 'Known products and specialized operating tools.',
    description: 'The known BCA portfolio. Product boundaries, canonical repositories, and launch claims remain governed and must not be inferred from this map.',
    nodeType: 'system-group',
    status: 'WORKBENCH',
    owner: 'Product governance',
    parentId: 'bca-os',
    capabilities: ['Product catalog', 'Dependency visibility', 'Boundary review'],
    dependencies: ['shared-services', 'conrad'],
    riskLevel: 'MEDIUM',
    decisionState: 'GOVERNED',
  }),
  node({
    id: 'knowledge-vault',
    name: 'BCA Knowledge Vault',
    shortDescription: 'Governed documents, decisions, evidence, citations, and freshness.',
    description: 'The company knowledge layer intended to provide source material, ownership, citations, dates, and permissions for Conrad and the explorer.',
    nodeType: 'platform-service',
    status: 'NURSERY',
    parentId: 'shared-services',
    capabilities: ['Source references', 'Decision records', 'Freshness tracking', 'Permissioned retrieval'],
    dependencies: ['bca-os'],
    agents: ['Conrad / EXPO'],
    workflows: ['Source registration', 'Citation retrieval', 'Freshness review'],
    riskLevel: 'HIGH',
    decisionState: 'ARCHITECTURE-LEVEL',
  }),
  node({
    id: 'model-router',
    name: 'Model Router',
    shortDescription: 'Provider-neutral AI gateway for approved model selection.',
    description: 'A proposed gateway that routes work according to task, privacy, cost, quality, and availability behind one governed contract.',
    nodeType: 'platform-service',
    status: 'NURSERY',
    parentId: 'shared-services',
    capabilities: ['Provider adapters', 'Fallback rules', 'Logging', 'Redaction', 'Cost measurement'],
    dependencies: ['bca-os'],
    agents: ['Conrad / EXPO'],
    workflows: ['Route task', 'Apply fallback', 'Record provider result'],
    riskLevel: 'HIGH',
    decisionState: 'ARCHITECTURE-LEVEL',
  }),
  node({
    id: 'agent-registry',
    name: 'Agent Registry',
    shortDescription: 'Governed record of roles, tools, permissions, owners, and health.',
    description: 'The future registry for approved agent roles, tool access, permissions, ownership, model assignment, and operating health.',
    nodeType: 'platform-service',
    status: 'NURSERY',
    parentId: 'shared-services',
    capabilities: ['Agent identity', 'Permissions', 'Ownership', 'Health records'],
    dependencies: ['bca-os', 'conrad'],
    workflows: ['Register agent', 'Approve permissions', 'Review health'],
    riskLevel: 'HIGH',
    decisionState: 'ARCHITECTURE-LEVEL',
    sourceReferences: ['Conrad Blueprint Explorer master build prompt'],
  }),
  node({
    id: 'workflow-engine',
    name: 'Workflow Engine',
    shortDescription: 'Approved automations, triggers, approvals, retries, and history.',
    description: 'The workflow layer for governed automations. Its specific implementation remains an architecture decision.',
    nodeType: 'platform-service',
    status: 'NURSERY',
    parentId: 'shared-services',
    capabilities: ['Triggers', 'Approval gates', 'Retries', 'Run history'],
    dependencies: ['bca-os', 'conrad'],
    riskLevel: 'HIGH',
    decisionState: 'ARCHITECTURE-LEVEL',
    sourceReferences: ['Conrad Blueprint Explorer master build prompt'],
  }),
  node({
    id: 'memory-fabric',
    name: 'Shared Memory Fabric',
    shortDescription: 'Cross-product permissioned memory layer.',
    description: 'A governed shared memory architecture requiring explicit tenancy, consent, provenance, retention, deletion, encryption, and product permissions.',
    nodeType: 'platform-service',
    status: 'NURSERY',
    parentId: 'shared-services',
    capabilities: ['Permissioned memory', 'Retention rules', 'Deletion controls', 'Provenance'],
    dependencies: ['bca-os', 'knowledge-vault'],
    workflows: ['Store memory', 'Retrieve memory', 'Delete memory', 'Audit provenance'],
    riskLevel: 'HIGH',
    decisionState: 'ARCHITECTURE-LEVEL',
  }),
  node({
    id: 'continuity-mode',
    name: 'Continuity Mode',
    shortDescription: 'Hybrid cloud and offline reliability architecture.',
    description: 'A reusable continuity principle for essential local capability, synchronization, conflict resolution, and graceful degradation.',
    nodeType: 'architecture-principle',
    status: 'NURSERY',
    parentId: 'shared-services',
    capabilities: ['Offline continuity', 'Synchronization', 'Conflict resolution', 'Recovery testing'],
    dependencies: ['bca-os'],
    environments: ['Cloud', 'Local'],
    workflows: ['Enter continuity mode', 'Synchronize on recovery'],
    riskLevel: 'HIGH',
    decisionState: 'ARCHITECTURE-LEVEL',
  }),
  node({
    id: 'trust-safety',
    name: 'Trust, Safety & Compliance',
    shortDescription: 'Governance gates for privacy, youth safety, liability, and approvals.',
    description: 'The control layer for product-specific safety requirements, approval gates, source traceability, and required human confirmation.',
    nodeType: 'governance-service',
    status: 'WORKBENCH',
    owner: 'Architecture and product governance',
    parentId: 'shared-services',
    capabilities: ['Approval gates', 'Source traceability', 'Human confirmation', 'Privacy controls'],
    dependencies: ['bca-os', 'knowledge-vault'],
    workflows: ['Review gated product', 'Record approval', 'Block unapproved release'],
    riskLevel: 'CRITICAL',
    decisionState: 'GOVERNED',
  }),
  node({
    id: 'shared-wallet',
    name: 'Shared BCA Wallet',
    shortDescription: 'Proposed cross-product credit system.',
    description: 'Accounting, purchase, consumption, refunds, expiration, fraud, and chargeback rules require architecture approval before implementation.',
    nodeType: 'platform-service',
    status: 'CRIB',
    parentId: 'shared-services',
    capabilities: ['Cross-product credits', 'Usage accounting', 'Refund rules', 'Fraud controls'],
    dependencies: ['bca-os'],
    riskLevel: 'CRITICAL',
    decisionState: 'ARCHITECTURE-LEVEL',
  }),
  node({
    id: 'live-avatar-engine',
    name: 'Live Avatar Agent Engine',
    shortDescription: 'Reusable voice, hearing, vision, gesture, and live interaction engine.',
    description: 'A reusable engine intended to support real-time avatar interaction across approved products, with Captain Culinary as the first customer.',
    nodeType: 'shared-engine',
    status: 'WORKBENCH',
    parentId: 'shared-services',
    capabilities: ['Voice', 'Hearing', 'Vision', 'Avatar motion', 'Gestures', 'Real-time interaction'],
    dependencies: ['model-router', 'continuity-mode', 'trust-safety'],
    workflows: ['Listen', 'Reason', 'Respond', 'Animate'],
    riskLevel: 'HIGH',
    decisionState: 'ARCHITECTURE-LEVEL',
    sourceReferences: ['BCA agent platform architecture'],
  }),
  node({
    id: 'blueprint-explorer',
    name: 'Conrad Blueprint Explorer',
    shortDescription: 'Governed, searchable architecture and dependency map.',
    description: 'A read-only V1 map with hierarchy, aligned levels, search, filters, node detail, relationship inspection, and JSON export.',
    nodeType: 'internal-interface',
    status: 'WORKBENCH',
    evidenceState: 'VERIFIED',
    owner: 'BCA OS',
    parentId: 'company-control',
    capabilities: ['Hierarchy map', 'Search', 'Status filters', 'Relationship view', 'JSON export'],
    dependencies: ['conrad', 'knowledge-vault'],
    repositories: ['Cmooreculinary/BCA-OS'],
    environments: ['Vercel-ready static frontend'],
    agents: ['Conrad / EXPO'],
    workflows: ['Inspect architecture', 'Export architecture'],
    riskLevel: 'MEDIUM',
    decisionState: 'GOVERNED',
    lastVerifiedAt: '2026-07-16',
    verifiedBy: 'Production build validation',
    sourceReferences: ['Conrad Blueprint Explorer master build prompt'],
  }),
  node({
    id: 'founder-console',
    name: 'BCA Founder Console / BCA-OPS HELM',
    shortDescription: 'Founder-facing operational interface under verification.',
    description: 'A founder control interface exists separately from the BCA-OS backend. Real telemetry integration and canonical naming remain to be confirmed.',
    nodeType: 'internal-interface',
    status: 'STAGING',
    evidenceState: 'VERIFIED',
    owner: 'Founder-controlled',
    parentId: 'company-control',
    capabilities: ['Founder view', 'Portfolio visibility', 'Operational controls'],
    dependencies: ['bca-os', 'conrad'],
    repositories: ['Cmooreculinary/blue-collar-apps-founders', 'Cmooreculinary/BCA-ops-agent'],
    environments: ['Vercel / v0 reported'],
    agents: ['Conrad / EXPO'],
    riskLevel: 'HIGH',
    lastVerifiedAt: '2026-07-14',
    verifiedBy: 'Portfolio audit',
  }),
  node({
    id: 'control-center',
    name: 'Conrad Control Center',
    shortDescription: 'Future operational cockpit built on the governed explorer.',
    description: 'A later cockpit for health, agent activity, incidents, launches, decision queues, cost, reliability, and founder briefings. It is not V1.',
    nodeType: 'internal-interface',
    status: 'CONCEPT',
    parentId: 'company-control',
    capabilities: ['Health overview', 'Incident queue', 'Decision queue', 'Founder briefing'],
    dependencies: ['blueprint-explorer', 'conrad', 'agent-registry', 'workflow-engine'],
    agents: ['Conrad / EXPO'],
    riskLevel: 'HIGH',
    decisionState: 'ARCHITECTURE-LEVEL',
    sourceReferences: ['Conrad Blueprint Explorer master build prompt'],
  }),
  node({ id: 'footruck-apollo', name: 'Footruck Apollo', shortDescription: 'Known BCA product; detailed status is outside this prototype.', description: 'Included as a known product without asserting unverified deployment, pricing, or roadmap details.', nodeType: 'product', owner: 'Product governance', parentId: 'product-suite', dependencies: ['shared-services'], repositories: ['Cmooreculinary/Footruck-Apollo'] }),
  node({ id: 'fusebox', name: 'FUSEBOX', shortDescription: 'Known BCA product with a frozen migration gate.', description: 'The canonical repository requires legacy dependency removal and BCA-controlled deployment work before redeployment approval.', nodeType: 'product', status: 'FROZEN', evidenceState: 'VERIFIED', owner: 'Product governance', parentId: 'product-suite', dependencies: ['trust-safety'], repositories: ['Cmooreculinary/Fusebox'], environments: ['Legacy deployment unconfirmed'], riskLevel: 'HIGH', decisionState: 'BLOCKED', lastVerifiedAt: '2026-07-14', verifiedBy: 'Repository audit' }),
  node({ id: 'brainforge', name: 'BrainForge', shortDescription: 'Known product with a documented two-service deployment blueprint.', description: 'The active repository contains frontend and backend services. Production endpoints and full workflow verification remain separate work.', nodeType: 'product', status: 'STAGING', evidenceState: 'VERIFIED', owner: 'Product governance', parentId: 'product-suite', dependencies: ['shared-services'], repositories: ['Cmooreculinary/BrainForge', 'Cmooreculinary/Brainforge-API'], environments: ['Render blueprint documented'], riskLevel: 'MEDIUM', lastVerifiedAt: '2026-07-14', verifiedBy: 'Repository audit' }),
  node({ id: 'margin-iq', name: 'Margin IQ', shortDescription: 'Professional-suite product with documented staged work.', description: 'Production behavior, persistence, and branch governance require verification before a live claim.', nodeType: 'product', status: 'STAGING', evidenceState: 'VERIFIED', owner: 'Product governance', parentId: 'product-suite', dependencies: ['shared-services'], repositories: ['Cmooreculinary/margin-IQ'], environments: ['Render configuration documented'], riskLevel: 'MEDIUM', lastVerifiedAt: '2026-07-14', verifiedBy: 'Repository audit' }),
  node({ id: 'venue-iq', name: 'Venue IQ', shortDescription: 'Professional-suite venue operations product.', description: 'Two repositories are documented. Canonical boundaries and a verified production deployment remain under review.', nodeType: 'product', status: 'STAGING', evidenceState: 'VERIFIED', owner: 'Product governance', parentId: 'product-suite', dependencies: ['shared-services'], repositories: ['Cmooreculinary/Venue-IQ', 'Cmooreculinary/venue-iq-dashboard'], environments: ['Render and Vercel / v0 reported'], riskLevel: 'MEDIUM', lastVerifiedAt: '2026-07-14', verifiedBy: 'Repository audit' }),
  node({ id: 'capkids', name: 'Captain Culinary Kids / CapKids', shortDescription: 'Child-focused culinary education product with COPPA gates.', description: 'CapKids requires parental consent, minimized child data, retention and deletion controls, content safety, and a supervised lesson path before release.', nodeType: 'product', status: 'WORKBENCH', evidenceState: 'VERIFIED', owner: 'Product governance', parentId: 'product-suite', capabilities: ['Culinary education', 'Parent and teacher controls', 'Curriculum progress'], dependencies: ['trust-safety', 'continuity-mode', 'live-avatar-engine'], repositories: ['Cmooreculinary/Captain-Culinary-Kids', 'Cmooreculinary/Captain-Culinary-Kids-June', 'Cmooreculinary/Caps-kids-AI-studio'], environments: ['AI Studio project verified', 'Production unconfirmed'], agents: ['Lesson Agent', 'Live Motion Agent', 'Safety Agent', 'Recipe Agent', 'Progress Agent', 'Parent / Teacher Agent'], workflows: ['Parental consent', 'Supervised lesson', 'Assessment', 'Progress review'], riskLevel: 'CRITICAL', decisionState: 'COPPA GATE', lastVerifiedAt: '2026-07-14', verifiedBy: 'Repository and portfolio audit' }),
  node({ id: 'captain-culinary', name: 'Captain Culinary', shortDescription: 'Professional and educational culinary coaching product and agent.', description: 'A Robot Chef coaching prototype is documented. Broader boundaries, routing, curriculum, and continuity remain governed work.', nodeType: 'product-agent', status: 'WORKBENCH', evidenceState: 'VERIFIED', owner: 'Product governance', parentId: 'product-suite', capabilities: ['Culinary coaching', 'Voice interaction', 'Vision-assisted guidance'], dependencies: ['model-router', 'continuity-mode', 'live-avatar-engine', 'trust-safety'], repositories: ['Cmooreculinary/robot_chef_app'], environments: ['Render blueprint documented', 'AI Studio projects reported'], agents: ['Captain Culinary'], workflows: ['Coach user', 'Evaluate task', 'Provide next step'], riskLevel: 'HIGH', lastVerifiedAt: '2026-07-14', verifiedBy: 'Repository audit' }),
  node({ id: 'restaurant-pro', name: 'Restaurant Pro / Restaurateur Pro', shortDescription: 'Professional product with naming and repository review required.', description: 'The product exists under multiple names and repositories. Canonical naming, repository selection, and a verified workflow remain unresolved.', nodeType: 'product', status: 'STAGING', evidenceState: 'VERIFIED', owner: 'Product governance', parentId: 'product-suite', dependencies: ['shared-services'], repositories: ['Cmooreculinary/Restaunteur-Pro', 'Cmooreculinary/restaurant-pro'], environments: ['Deployment reported failed'], riskLevel: 'HIGH', decisionState: 'NAMING REVIEW', lastVerifiedAt: '2026-07-14', verifiedBy: 'Portfolio audit' }),
  node({ id: 'allergen-shield', name: 'AllergenShield', shortDescription: 'Liability-gated professional product.', description: 'AllergenShield must not guarantee allergen safety. Release requires liability language, source traceability, human confirmation, legal review, and insurance approval.', nodeType: 'product', status: 'FROZEN', evidenceState: 'VERIFIED', owner: 'Product governance', parentId: 'product-suite', capabilities: ['Source traceability', 'Human confirmation workflow'], dependencies: ['trust-safety', 'knowledge-vault'], repositories: ['Cmooreculinary/alergen_shield'], environments: ['Deployment reported; release not approved'], workflows: ['Review source', 'Human confirmation', 'Liability gate'], riskLevel: 'CRITICAL', decisionState: 'LIABILITY GATE', lastVerifiedAt: '2026-07-14', verifiedBy: 'Portfolio audit' }),
  node({ id: 'round-table', name: 'Round Table', shortDescription: 'Shared reasoning and collaboration product.', description: 'A primary full-stack repository and alternate implementation are documented. Production endpoints, storage, and integrations require verification.', nodeType: 'product', status: 'STAGING', evidenceState: 'VERIFIED', owner: 'Product governance', parentId: 'product-suite', capabilities: ['Multi-perspective sessions', 'Collaboration'], dependencies: ['shared-services', 'model-router'], repositories: ['Cmooreculinary/BCAz-Roundtable', 'Cmooreculinary/round-table'], environments: ['Render configuration documented'], riskLevel: 'MEDIUM', lastVerifiedAt: '2026-07-14', verifiedBy: 'Repository audit' }),
  node({ id: 'maestro-vaultspace', name: 'Maestro + VaultSpace', shortDescription: 'Life-management orchestration and secure memory products.', description: 'Canonical naming, durable storage, recovery, permissions, and a complete daily workflow require verification.', nodeType: 'product-group', status: 'WORKBENCH', owner: 'Product governance', parentId: 'product-suite', capabilities: ['Capture', 'Classify', 'Prioritize', 'Schedule', 'Secure document memory'], dependencies: ['memory-fabric', 'workflow-engine', 'trust-safety'], repositories: ['Cmooreculinary/Maestro', 'Cmooreculinary/Maestro-Hub'], environments: ['AI Studio project reported'], agents: ['Maestro'], workflows: ['Capture', 'Classify', 'Prioritize', 'Schedule', 'Complete'], riskLevel: 'HIGH' }),
  node({ id: 'plate-me', name: 'Plate Me', shortDescription: 'Known product with deployment recovery work outstanding.', description: 'Repository evidence exists, while the deployment and complete user path remain unverified.', nodeType: 'product', status: 'WORKBENCH', evidenceState: 'VERIFIED', owner: 'Product governance', parentId: 'product-suite', dependencies: ['shared-services'], repositories: ['Cmooreculinary/Plate-Me'], environments: ['Deployment reported failed'], riskLevel: 'MEDIUM', lastVerifiedAt: '2026-07-14', verifiedBy: 'Portfolio audit' }),
  node({ id: 'dusk', name: 'DUSK', shortDescription: 'Known BCA product; deployment status is not asserted here.', description: 'Included as a known product without defining detailed scope, deployment status, pricing, or roadmap.', nodeType: 'product', evidenceState: 'VERIFIED', owner: 'Product governance', parentId: 'product-suite', dependencies: ['shared-services'], repositories: ['Cmooreculinary/Dusk'], sourceReferences: ['GitHub repository register'] }),
  node({ id: 'vine-barrel', name: 'Vine & Barrel', shortDescription: 'Known concept; implementation status is unverified.', description: 'Included as a known concept without an asserted repository, deployment, pricing, or roadmap.', nodeType: 'product', status: 'CONCEPT', owner: 'Product governance', parentId: 'product-suite', decisionState: 'ARCHITECTURE-LEVEL', sourceReferences: ['BCA ecosystem catalog'] }),
  node({ id: 'permit-pilot', name: 'Permit Pilot', shortDescription: 'Known concept; implementation status is unverified.', description: 'Included as a known concept without an asserted repository, deployment, pricing, or roadmap.', nodeType: 'product', status: 'CONCEPT', owner: 'Product governance', parentId: 'product-suite', decisionState: 'ARCHITECTURE-LEVEL', sourceReferences: ['BCA ecosystem catalog'] }),
]

export const relationships = nodes.flatMap((item) =>
  item.dependencies.map((dependencyId) => ({
    sourceNodeId: item.id,
    targetNodeId: dependencyId,
    relationshipType: 'depends-on',
    direction: 'outbound',
    description: `${item.name} depends on ${dependencyId}.`,
    criticality: item.riskLevel,
    verificationState: item.evidenceState,
  })),
)
